version: '3.9'
services:

  tyk-edge-pump-1:
    image: tykio/tyk-pump-docker-pub:v1.11
    container_name: tyk-edge-pump-1
    env_file:
      - ./confs/tyk-edge-pump.env
    environment:
      - TYK_PMP_OMITCONFIGFILE=true
      - TYK_PMP_PUMPS_HYBRID_META_RPCKEY=${TYK_GW_SLAVEOPTIONS_RPCKEY}
      - TYK_PMP_PUMPS_HYBRID_META_APIKEY=${TYK_GW_SLAVEOPTIONS_APIKEY}
      - TYK_PMP_ANALYTICSSTORAGECONFIG_ADDRS=tyk-edge-redis-1:6379
    networks:
      - tyk

  tyk-edge-redis-1:
    image: redis
    container_name: tyk-edge-redis-1
    ports:
      - "6379"
    volumes:
      - redis-edge-data-1:/data
    networks:
      - tyk

  tyk-edge-gateway-1:
    image: tykio/tyk-gateway:v5.5
    container_name: tyk-edge-gateway-1
    ports:
      - "8090:8090"
    environment:
      - TYK_GW_LISTENPORT=8090
      - TYK_GW_ANALYTICSSTORAGE_HOST=tyk-edge-redis-1
      - TYK_GW_ANALYTICSSTORAGE_PORT=6379
      - TYK_GW_STORAGE_ADDRS=tyk-edge-redis-1:6379
      - TYK_GW_SLAVEOPTIONS_RPCKEY=${TYK_GW_SLAVEOPTIONS_RPCKEY}
      - TYK_GW_SLAVEOPTIONS_APIKEY=${TYK_GW_SLAVEOPTIONS_APIKEY}
      - TYK_GW_SLAVEOPTIONS_GROUPID="ES01"
    env_file:
      - ./confs/tyk.env
    networks:
      - tyk

  tyk-edge-pump-2:
    image: tykio/tyk-pump-docker-pub:v1.11
    container_name: tyk-edge-pump-2
    env_file:
      - ./confs/tyk-edge-pump.env
    environment:
      - TYK_PMP_OMITCONFIGFILE=true
      - TYK_PMP_PUMPS_HYBRID_META_RPCKEY=${TYK_GW_SLAVEOPTIONS_RPCKEY}
      - TYK_PMP_PUMPS_HYBRID_META_APIKEY=${TYK_GW_SLAVEOPTIONS_APIKEY}
      - TYK_PMP_ANALYTICSSTORAGECONFIG_ADDRS=tyk-edge-redis-2:6379 
    networks:
      - tyk

  tyk-edge-redis-2:
    image: redis
    container_name: tyk-edge-redis-2
    ports:
      - "6379"
    volumes:
      - redis-edge-data-2:/data
    networks:
      - tyk

  tyk-edge-gateway-2:
    image: tykio/tyk-gateway:v5.5
    container_name: tyk-edge-gateway-2
    ports:
      - "8091:8091"
    environment:
      - TYK_GW_LISTENPORT=8091
      - TYK_GW_ANALYTICSSTORAGE_HOST=tyk-edge-redis-2
      - TYK_GW_ANALYTICSSTORAGE_PORT=6379
      - TYK_GW_STORAGE_ADDRS=tyk-edge-redis-2:6379
      - TYK_GW_SLAVEOPTIONS_RPCKEY=${TYK_GW_SLAVEOPTIONS_RPCKEY}
      - TYK_GW_SLAVEOPTIONS_APIKEY=${TYK_GW_SLAVEOPTIONS_APIKEY}
      - TYK_GW_SLAVEOPTIONS_GROUPID="ES01"
    env_file:
      - ./confs/tyk.env
    networks:
      - tyk

volumes:
  redis-edge-data-1:
  redis-edge-data-2:

networks:
  tyk: